const nav = document.querySelector('#nav')
     ul = document.getElementById('list')
     li = document.getElementById('item1')
     li2 = document.getElementById('item2')
     li3 = document.getElementById('item3')
 section = document.querySelector('#section')
    form = document.querySelector('#formulario')
  input1 = document.querySelector('#input1')
  input2 = document.querySelector('#input2')

